DROP TABLE IF EXISTS DOMICILIOS;
CREATE TABLE DOMICILIOS(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CALLE VARCHAR(50) NOT NULL,
    NUMERO INT NOT NULL,
    LOCALIDAD VARCHAR(50) NOT NULL,
    PROVINCIA VARCHAR(50) NOT NULL);

DROP TABLE IF EXISTS PACIENTES;
CREATE TABLE PACIENTES(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    APELLIDO VARCHAR(50) NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    DNI VARCHAR(50) NOT NULL,
    FECHA_INGRESO DATE NOT NULL,
    ID_DOMICILIO INT);

DROP TABLE IF EXISTS ODONTOLOGOS;
CREATE TABLE ODONTOLOGOS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    MATRICULA INT NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    APELLIDO VARCHAR(50) NOT NULL
);

INSERT INTO DOMICILIOS
VALUES (DEFAULT, 'DOMICILIO 1', 1123, 'SAN PEDRO', 'JUJUY'),
       (DEFAULT, 'DOMICILIO 2', 1123, 'FLORES', 'BOGOTA');

INSERT INTO PACIENTES
VALUES  (DEFAULT, 'PACIENTE 1', 'FULANITO', '123456', '2024-02-15', 1),
        (DEFAULT, 'PACIENTE 2', 'MENGANITO', '9898765', '2024-02-16', 2);

INSERT INTO ODONTOLOGOS
VALUES  (DEFAULT, 5465657, 'PEPITO', 'PEREZ'),
        (DEFAULT, 54546456, 'SUTANITO', 'RIOS');